name: Pre-commit Starter Check

on:
  push:
    branches: [ main, master ] # Adjust branches as needed
  pull_request:
    branches: [ main, master ] # Adjust branches as needed

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a specific version if required, e.g., '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit pre-commit-starter

    - name: Generate pre-commit config
      run: pre-commit-starter --force # Use --force to ensure config is generated

    - name: Install pre-commit hooks
      run: pre-commit install-hooks # Installs hooks based on the generated config

    - name: Run pre-commit checks
      run: pre-commit run --all-files # Run checks on all files
