---
name: Pre-Commit Starter Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or your desired Python version

      - name: Install dependencies
        run: |
          pip install pre-commit pre-commit-starter

      - name: Generate pre-commit config
        run: pre-commit-starter --force # Use --force to ensure config is generated

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
